FROM ubuntu:focal

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

WORKDIR /home/app

COPY package*.json ./

RUN npm install
COPY . .

ENV MONGODB_URI=mongodb://mongo:27017/Notifyme
ENV KAFKA_BROKER=kafka:9092
EXPOSE 3001
CMD ["npx", "nodemon", "index.js"]